// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmy24djsF9ZmJOvTUVKw_Hz5nLrMJmo70',
    appId: '1:39402500214:web:b4616cb4a6fbe9675a2f57',
    messagingSenderId: '39402500214',
    projectId: 'truckive',
    authDomain: 'truckive.firebaseapp.com',
    storageBucket: 'truckive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWa_CuwOGblcnEhiOTt0n6_zoOSAS08M',
    appId: '1:39402500214:android:1a8d3401c6564a985a2f57',
    messagingSenderId: '39402500214',
    projectId: 'truckive',
    storageBucket: 'truckive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNAQmXsGpUTHOu4yrntqAVLecyDzZQ3As',
    appId: '1:39402500214:ios:69bdf4bd3971cc765a2f57',
    messagingSenderId: '39402500214',
    projectId: 'truckive',
    storageBucket: 'truckive.appspot.com',
    iosClientId:
        '39402500214-e065vbgpmq7f4mo74997sv5fgsm7qkkl.apps.googleusercontent.com',
    iosBundleId: 'com.snapsid.loginuicolors',
  );
}
